# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, binary, hmatrix, QuickCheck, random, split }:

cabal.mkDerivation (self: {
  pname = "perceptron";
  version = "0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ binary hmatrix QuickCheck random split ];
  meta = {
    platforms = self.ghc.meta.platforms;
  };
})
